### ISSUE TITLE
Getting  error "Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener"

### ISSUE THREAD

**Issue by anirbanpuky** [reportportal/agent-java-testNG#182]
While running the test in Azure Devops Pipeline, I am getting the below error 
"Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener" 
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process

I have mentioned the listener in my POM.xml file only.
Please help.

Dependencies :

            <dependency>
                <groupId>com.epam.reportportal</groupId>
                <artifactId>agent-java-testng</artifactId>
                <version>5.1.1</version>
            </dependency>
            <dependency>
                <groupId>com.epam.reportportal</groupId>
                <artifactId>logger-java-log4j</artifactId>
                <version>5.1.4</version>
            </dependency>

**Comment by GavinHewittQA** [comment]
I had the exact same issue, but have zero doubt it was my configuration at fault, 5.1.0 fine, 5.1.1 generates the above error. 
 
Watching this thread in interest.

**Comment by anirbanpuky** [comment]
This is the error log I am getting.

Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
2022-02-12T09:56:55.0711137Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
2022-02-12T09:56:55.0712063Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
2022-02-12T09:56:55.0712934Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
2022-02-12T09:56:55.0714681Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
2022-02-12T09:56:55.0715732Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
2022-02-12T09:56:55.0716409Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
2022-02-12T09:56:55.0717008Z [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2022-02-12T09:56:55.0717571Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
2022-02-12T09:56:55.0718158Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
2022-02-12T09:56:55.0719648Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
2022-02-12T09:56:55.0723251Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2022-02-12T09:56:55.0724101Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
2022-02-12T09:56:55.0724808Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
2022-02-12T09:56:55.0726155Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
2022-02-12T09:56:55.0727200Z [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
2022-02-12T09:56:55.0727668Z [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
2022-02-12T09:56:55.0728141Z [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
2022-02-12T09:56:55.0728581Z [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
2022-02-12T09:56:55.0729009Z [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
2022-02-12T09:56:55.0729762Z [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
2022-02-12T09:56:55.0730216Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-02-12T09:56:55.0730944Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-02-12T09:56:55.0732262Z [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-12T09:56:55.0732802Z [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-02-12T09:56:55.0733284Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
2022-02-12T09:56:55.0733807Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
2022-02-12T09:56:55.0734358Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
2022-02-12T09:56:55.0734886Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by HardNorth** [comment]
@GavinHewittQA We sometimes change our dependencies from version-to-version due to critical security vulnerabilities and `5.1.1` is exact that case. So this might happen if you have strong dependency on compromised libraries. I also can say that version `5.1.1` already in use by hundreds of users, so I'm very skeptical about any claim that something wrong with it. To make me change my mind you have to provide very strong evidences. I don't see them here.

@anirbanpuky There is still no information about the root cause of the error. Please provide original exception not what's Maven gives you. Use Maven debug mode if necessary.

**Comment by GavinHewittQA** [comment]
> @GavinHewittQA We sometimes change our dependencies from version-to-version due to critical security vulnerabilities and `5.1.1` is exact that case. So this might happen if you have strong dependency on compromised libraries. I also can say that version `5.1.1` already in use by hundreds of users, so I'm very skeptical about any claim that something wrong with it. To make me change my mind you have to provide very strong evidences. I don't see them here.
> 
> @anirbanpuky There is still no information about the root cause of the error. Please provide original exception not what's Maven gives you. Use Maven debug mode if necessary.

Fully agree its more than likely my configuration :)     When i get serious time ill try work it out and update thread with findings, good or bad.

**Comment by varundunga** [comment]
@HardNorth Im also getting this error.
`
# Created at 2022-02-14T22:33:34.605
org.testng.TestNGException: 
Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:59)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
	at org.testng.TestNG.addListeners(TestNG.java:993)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:950)
	at org.testng.TestNG.initializeEverything(TestNG.java:1041)
	at org.testng.TestNG.run(TestNG.java:1052)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
	... 15 more
Caused by: java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:542)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:430)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:430)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)
	at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:93)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:33)
	... 20 more


`

**Comment by HardNorth** [comment]
@varundunga You are using old `OkHttpClient`. Most likely due to old Selenium dependency. Please update it on at least version `3.141.0`.
Actually that's a duplicate of: https://github.com/reportportal/agent-java-testNG/issues/173

**Comment by iKabi** [comment]
Hi @HardNorth, with version 5.1.0 tests worked fine in azure pipeline. However, facing same issue with version **5.1.1**. Error seen:
```
2022-03-08T07:03:10.2012561Z [ERROR] Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
2022-03-08T07:03:10.2013320Z [ERROR] org.testng.TestNGException: 
2022-03-08T07:03:10.2013724Z [ERROR] 
2022-03-08T07:03:10.2014152Z [ERROR] Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
2022-03-08T07:03:10.2014696Z [ERROR] 	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
2022-03-08T07:03:10.2015274Z [ERROR] 	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:59)
2022-03-08T07:03:10.2015810Z [ERROR] 	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
2022-03-08T07:03:10.2016281Z [ERROR] 	at org.testng.TestNG.setListenerClasses(TestNG.java:672)
2022-03-08T07:03:10.2016688Z [ERROR] 	at org.testng.TestNG.configure(TestNG.java:1510)
2022-03-08T07:03:10.2017267Z [ERROR] 	at org.testng.TestNG.configure(TestNG.java:1717)
2022-03-08T07:03:10.2017782Z [ERROR] 	at org.apache.maven.surefire.testng.conf.TestNGMapConfigurator.configure(TestNGMapConfigurator.java:57)
2022-03-08T07:03:10.2018374Z [ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:280)
2022-03-08T07:03:10.2018925Z [ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
2022-03-08T07:03:10.2019495Z [ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
2022-03-08T07:03:10.2020052Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2022-03-08T07:03:10.2020618Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2022-03-08T07:03:10.2021230Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2022-03-08T07:03:10.2021742Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2022-03-08T07:03:10.2022205Z [ERROR] Caused by: java.lang.reflect.InvocationTargetException
2022-03-08T07:03:10.2022638Z [ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2022-03-08T07:03:10.2023237Z [ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2022-03-08T07:03:10.2023912Z [ERROR] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-03-08T07:03:10.2024543Z [ERROR] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2022-03-08T07:03:10.2025056Z [ERROR] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2022-03-08T07:03:10.2025589Z [ERROR] 	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
2022-03-08T07:03:10.2025965Z [ERROR] 	... 13 more
2022-03-08T07:03:10.2026245Z [ERROR] Caused by: java.lang.ExceptionInInitializerError
2022-03-08T07:03:10.2026729Z [ERROR] 	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
2022-03-08T07:03:10.2027303Z [ERROR] 	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:33)
2022-03-08T07:03:10.2027735Z [ERROR] 	... 19 more
2022-03-08T07:03:10.2028143Z [ERROR] Caused by: java.lang.IllegalStateException: Duplicate key agent.jobstatus (attempted merging values Succeeded and Succeeded)
2022-03-08T07:03:10.2028716Z [ERROR] 	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
2022-03-08T07:03:10.2029262Z [ERROR] 	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
2022-03-08T07:03:10.2029801Z [ERROR] 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
2022-03-08T07:03:10.2030409Z [ERROR] 	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1625)
2022-03-08T07:03:10.2030971Z [ERROR] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2022-03-08T07:03:10.2031503Z [ERROR] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2022-03-08T07:03:10.2032236Z [ERROR] 	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1650)
2022-03-08T07:03:10.2032904Z [ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-03-08T07:03:10.2033440Z [ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-03-08T07:03:10.2034000Z [ERROR] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2022-03-08T07:03:10.2034530Z [ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-03-08T07:03:10.2035300Z [ERROR] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
2022-03-08T07:03:10.2035878Z [ERROR] 	at com.epam.reportportal.utils.properties.PropertiesLoader.normalizeOverrides(PropertiesLoader.java:177)
2022-03-08T07:03:10.2036513Z [ERROR] 	at com.epam.reportportal.utils.properties.PropertiesLoader.overrideWith(PropertiesLoader.java:188)
2022-03-08T07:03:10.2037150Z [ERROR] 	at com.epam.reportportal.utils.properties.PropertiesLoader.loadProperties(PropertiesLoader.java:63)
2022-03-08T07:03:10.2037772Z [ERROR] 	at com.epam.reportportal.utils.properties.PropertiesLoader.lambda$load$0(PropertiesLoader.java:78)
2022-03-08T07:03:10.2038337Z [ERROR] 	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
2022-03-08T07:03:10.2038898Z [ERROR] 	at com.epam.reportportal.utils.properties.PropertiesLoader.getProperty(PropertiesLoader.java:154)
2022-03-08T07:03:10.2039560Z [ERROR] 	at com.epam.reportportal.listeners.ListenerParameters.<init>(ListenerParameters.java:182)
2022-03-08T07:03:10.2040109Z [ERROR] 	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:402)
2022-03-08T07:03:10.2040648Z [ERROR] 	at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:93)
2022-03-08T07:03:10.2041012Z [ERROR] 	... 21 more
```
