### ISSUE TITLE
Getting Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener

### ISSUE THREAD

**Issue by php-del** [reportportal/agent-java-testNG#189]
Following are my pom.xml dependencies and listener configuration

<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>5.1.3</version>
		</dependency>
		
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-logback</artifactId>
			<version>5.1.3</version>
		</dependency>
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>src/test/resources/cisuite/${suitefile}</suiteXmlFile>
					</suiteXmlFiles>
					<systemPropertyVariables>
						<env>${env}</env>
						<browser>${browser}</browser>
						<suitefile>${suitefile}</suitefile>
						<suite>${suite}</suite>
						<test_region>${test_region}</test_region>
						<updateBugInJira>${updateBugInJira}</updateBugInJira>
						<updateTestRail>${updateTestRail}</updateTestRail>
					</systemPropertyVariables>
					<properties>
						<property>
							<name>usedefaultlisteners</name>
							<value>true</value> 
						</property>
						<property>
							<name>listener</name>
							<value>com.epam.reportportal.testng.ReportPortalTestNGListener</value>
						</property>
					</properties>
I am getting the following error.
 Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] 
[ERROR] Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)

I am using Cucumber with TestNG and the following is the reportportal.properties file kept at src/test/resources 

rp.endpoint = http://localhost:8080
rp.uuid = f6ce83b2-e26f-4fc9-9f03-03a9c163ece7
rp.launch = superadmin_TEST_EXAMPLE
rp.project = superadmin_personal
rp.attributes=key:value;value
rp.reporting.async=true

When I do keep the listener under properties out of the configuration as shown below, I do not get any error, and tests are executed but I see nothing in the test launch section of the report portal UI. 
<groupId>com.morningstar.indexes</groupId>
	<artifactId>market-data-ui-tests</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<suitefile>SmokeSuite_qa.xml</suitefile>
		<env>qa</env>
		<browser>localChrome</browser>
		<suite>Smoke</suite>
		<test_region>us-east-1</test_region>
		<updateBugInJira>false</updateBugInJira>
		<updateTestRail>true</updateTestRail>
               <listener> com.epam.reportportal.testng.ReportPortalTestNGListener</listener>
	</properties>

Can someone please help me integrating my Test results to Report portal Dashboard?

**Comment by HardNorth** [comment]
@php-del Please provide detailed logs or a project to reproduce the issue.
Maven logging configuration:
https://maven.apache.org/surefire/maven-surefire-plugin/examples/logging.html

**Comment by php-del** [comment]
[Log.txt](https://github.com/reportportal/agent-java-testNG/files/9724497/Log.txt)
Attached is the detailed log

**Comment by HardNorth** [comment]
@php-del OK, found this in your Log:
```
Caused by: java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(Ljava/time/Duration;)Lokhttp3/OkHttpClient$Builder;
```

This usually happens when someone use outdated Selenium version. Since Selenium uses the same HTTP client as Report Portal. To fix that you need to update Selenium version on at least version `3.141.0`.

This actually duplicate of the following issues:
https://github.com/reportportal/examples-java/issues/61
https://github.com/reportportal/client-java/issues/182
