### ISSUE TITLE
Random Exceptions in parallel of 500 tests 

### ISSUE THREAD

**Issue by yoavgeva** [reportportal/agent-java-testNG#37]
**Describe the bug**
Running 400-500 Tests in parallel with threadCount of 60 with TestNG Java 

Tests randomly fail and stop on ReportPortalException (in logs) (sometimes 1 tests sometimes 40 tests)
In ReportPortal Website I see them as interrupted tests when the launch stop (with force) and when the tests finish running the website still show those tests IN PROGRESS 
My question is, how to handle this kind of error? how can I debug it 

the pom.xml
 ```
<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>4.2.1-BETA</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>4.0.1</version>
        </dependency>
```

**Expected behaviour**
To not fail randomly

**Logs**
SEVERE: [142] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish test item is not allowed. Test item '5c7cfc202ab79c000160eae8' has descendants with 'IN_PROGRESS' status. All descendants '[beforeClassInits, beforeMethods, addNewTemplateVisiblityWorkspace, beforeMethods, addNewTemplateVisiblityWorkspace, afterClassActions]'
Error Type: FINISH_ITEM_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Versions:**
 - OS, Browser
MacOS High Sierra, Chrome Browser 
 - The version of RP [find it under Login form, copy as is]

Current version: Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Comment by filland** [comment]
@yoavgeva Hello, could you provide more info on how to reproduce your issue (e.g. setting for testng runner) ?

**Comment by yoavgeva** [comment]
after an investigation on my part, it seems an issue with a framework I received.
