### ISSUE TITLE
Getting Random error - Report portal is not functioning correctly. Response is not json

### ISSUE THREAD

**Issue by mangeshrane** [reportportal/agent-java-testNG#42]
When running tests using testNg getting Report portal is not functioning correctly. Response is not json error.

com.epam.reportportal.exception.InternalReportPortalClientException: Report portal is not functioning correctly. Response is not json
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:88)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by gaurav-singh** [comment]
Are you still facing this issue? Can you post more details around what version of report portal you are using and a sample test to reproduce the issue?

**Comment by HardNorth** [comment]
Closed due to inactivity.
