### ISSUE TITLE
Report portal exception is not handled properly which leads failure to create testng report

### ISSUE THREAD

**Issue by ssethy** [reportportal/agent-java-testNG#56]
There are many instances where report portal excepts some value or due to some validations report portal throws exception but then this is not handled properly which cause failure in testng report creation. It leads complete failure to build. To avoid such issue we had to remove report portal listener itself.

This issue is high priority and should be resolved.

The error logs can be found as below: 

18:53:59 06:23:59.310 [main] INFO  c.m.a.cms.helper.APIHelperUtils - WRITING THE DATA INTO JSON FILE /tmp/testcaseresult.json
18:53:59 06:23:59.315 [RxComputationThreadPool-4] ERROR c.e.r.utils.SubscriptionUtils - [28] ReportPortal Finish test item execution error
18:53:59 com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
18:53:59 Status code: 406
18:53:59 Status message: Not Acceptable
18:53:59 Error Message: Finish time 'Thu Jan 01 00:00:00 UTC 1970' is earlier than start time 'Tue Aug 13 13:15:24 UTC 2019' for resource with ID '5d52b8199bd1160001b8e043'
18:53:59 Error Type: FINISH_TIME_EARLIER_THAN_START_TIME
18:53:59 
18:53:59 	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83) ~[client-java-4.0.10.jar:na]
18:53:59 	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59) ~[client-java-4.0.10.jar:na]
18:53:59 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517) ~[client-java-4.0.10.jar:na]
18:53:59 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.Maybe.subscribe(Maybe.java:4096) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.Maybe.subscribe(Maybe.java:4096) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.1.16.jar:na]
18:53:59 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_144]
18:53:59 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
18:53:59 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
18:53:59 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
18:53:59 06:23:59.315 [RxComputationThreadPool-2] ERROR c.e.r.utils.SubscriptionUtils - [17] ReportPortal Finish test item execution error
18:53:59 com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
18:53:59 Status code: 406
18:53:59 Status message: Not Acceptable
18:53:59 Error Message: Finish time 'Thu Jan 01 00:00:00 UTC 1970' is earlier than start time 'Tue Aug 13 13:21:31 UTC 2019' for resource with ID '5d52b9899bd1160001b8f454'
18:53:59 Error Type: FINISH_TIME_EARLIER_THAN_START_TIME
18:53:59 
18:53:59 	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83) ~[client-java-4.0.10.jar:na]
18:53:59 	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59) ~[client-java-4.0.10.jar:na]
18:53:59 	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517) ~[client-java-4.0.10.jar:na]
18:53:59 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.Maybe.subscribe(Maybe.java:4096) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.Maybe.subscribe(Maybe.java:4096) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.1.16.jar:na]
18:53:59 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.1.16.jar:na]
18:53:59 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_144]
18:53:59 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
18:53:59 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
18:53:59 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
18:54:00 
18:54:00 Results :
18:54:00 
18:54:00 Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
18:54:00 
18:54:00 [INFO] ------------------------------------------------------------------------
18:54:00 [INFO] BUILD FAILURE
18:54:00 [INFO] ------------------------------------------------------------------------
18:54:00 [INFO] Total time: 01:24 h
18:54:00 [INFO] Finished at: 2019-08-13T06:23:59-07:00
18:54:00 [INFO] Final Memory: 83M/1008M
18:54:00 [INFO] ------------------------------------------------------------------------
18:54:00 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cms-cmsfr: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
18:54:00 [ERROR] java.lang.IllegalArgumentException: ItemID should not be null
18:54:00 [ERROR] at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
18:54:00 [ERROR] at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:247)
18:54:00 [ERROR] at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:152)
18:54:00 [ERROR] at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:93)
18:54:00 [ERROR] at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
18:54:00 [ERROR] at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:210)
18:54:00 [ERROR] at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:814)
18:54:00 [ERROR] at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
18:54:00 [ERROR] at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
18:54:00 [ERROR] at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
18:54:00 [ERROR] at java.util.ArrayList.forEach(ArrayList.java:1249)
18:54:00 [ERROR] at org.testng.TestRunner.privateRun(TestRunner.java:770)
18:54:00 [ERROR] at org.testng.TestRunner.run(TestRunner.java:591)
18:54:00 [ERROR] at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
18:54:00 [ERROR] at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
18:54:00 [ERROR] at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
18:54:00 [ERROR] at org.testng.SuiteRunner.run(SuiteRunner.java:304)
18:54:00 [ERROR] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
18:54:00 [ERROR] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
18:54:00 [ERROR] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
18:54:00 [ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
18:54:00 [ERROR] at org.testng.TestNG.runSuites(TestNG.java:1032)
18:54:00 [ERROR] at org.testng.TestNG.run(TestNG.java:1000)
18:54:00 [ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
18:54:00 [ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
18:54:00 [ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
18:54:00 [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
18:54:00 [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
18:54:00 [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
18:54:00 [ERROR] -> [Help 1]
18:54:00 [ERROR] 
18:54:00 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
18:54:00 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
18:54:00 [ERROR] 
18:54:00 [ERROR] For more information about the errors and possible solutions, please read the following articles:
18:54:00 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
18:54:01 
18:54:01 [SSH] completed
18:54:01 [SSH] exit-status: 0
18:54:01 
18:54:01 [SSH] script:

**Comment by HardNorth** [comment]
We found a single way to reproduce that. The issue caused by an exception in a DataProvider, in which case TestNG skips Test listener execution. That's not an RP issue.

Since version 7.1.1 they start re-throwing that Exception and now we can think how to handle that situation in our client/agent correctly. Anyway the fix will be here no sooner than 5.1.
