### ISSUE TITLE
Error when TestNG suite contains more than one <test> section

### ISSUE THREAD

**Issue by cheryomushkin** [reportportal/agent-java-testNG#7]
```
[2017-04-12 12:34:57,362] [DEBUG] [I/O dispatcher 3-28] ReportPortal item with ID '58edf4c1adbe1d00073e0c25' has been created
[2017-04-12 12:34:57,362] [DEBUG] [I/O dispatcher 4-29] ReportPortal item with ID '58edf4c1adbe1d00073e0c23' has been created
io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Reporting for item 58edf4a6adbe1d00073e0305 already finished. Please, check item status.
Error Type: REPORTING_ITEM_ALREADY_FINISHED

	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableCache.onError(CompletableCache.java:81)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	at io.reactivex.internal.operators.completable.CompletableConcatIterable$ConcatInnerObserver.onError(CompletableConcatIterable.java:72)
	at io.reactivex.internal.operators.completable.CompletableCache.subscribeActual(CompletableCache.java:64)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableConcatIterable$ConcatInnerObserver.next(CompletableConcatIterable.java:119)
	at io.reactivex.internal.operators.completable.CompletableConcatIterable.subscribeActual(CompletableConcatIterable.java:47)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableCache.subscribeActual(CompletableCache.java:59)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.Scheduler$1.run(Scheduler.java:138)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Reporting for item 58edf4a6adbe1d00073e0305 already finished. Please, check item status.
Error Type: REPORTING_ITEM_ALREADY_FINISHED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 more
Exception in thread "RxCachedThreadScheduler-10" io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Reporting for item 58edf4a6adbe1d00073e0305 already finished. Please, check item status.
Error Type: REPORTING_ITEM_ALREADY_FINISHED

	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableCache.onError(CompletableCache.java:81)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	at io.reactivex.internal.operators.completable.CompletableConcatIterable$ConcatInnerObserver.onError(CompletableConcatIterable.java:72)
	at io.reactivex.internal.operators.completable.CompletableCache.subscribeActual(CompletableCache.java:64)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableConcatIterable$ConcatInnerObserver.next(CompletableConcatIterable.java:119)
	at io.reactivex.internal.operators.completable.CompletableConcatIterable.subscribeActual(CompletableConcatIterable.java:47)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableCache.subscribeActual(CompletableCache.java:59)
	at io.reactivex.Completable.subscribe(Completable.java:1634)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.Scheduler$1.run(Scheduler.java:138)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Reporting for item 58edf4a6adbe1d00073e0305 already finished. Please, check item status.
Error Type: REPORTING_ITEM_ALREADY_FINISHED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 more
```

If there is a single <test> section then everything is OK.
```
<suite name="Tests" verbose="2" configfailurepolicy="continue" parallel="classes" thread-count="10">
    <test name="Validation">
        <packages>
            <package name="com.validate"/>
        </packages>
    </test>
</suite>
```
And the following will produce REPORTING_ITEM_ALREADY_FINISHED error:
```
<suite name="Tests" verbose="2" configfailurepolicy="continue" parallel="classes" thread-count="10">
    <test name="Validation">
        <packages>
            <package name="com.validate"/>
        </packages>
    </test>
    <test name="Work">
        <packages>
            <package name="com.work"/>
        </packages>
    </test>
</suite>
```

**Comment by avarabyeu** [comment]
@cheryomushkin could you please post some code or prepare some demo project to be able to reproduce an issue

**Comment by avarabyeu** [comment]
@cheryomushkin which version of client do use?

**Comment by cheryomushkin** [comment]
Following are the components I use:
```
'com.epam.reportportal:agent-java-testng:3.0.0-BETA-6'
'com.epam.reportportal:client-java:3.0.0-RC1'
'com.epam.reportportal:commons-model:3.0.0-RC1'
'com.epam.reportportal:logger-java-logback:3.0.0-BETA-1'
```

I will try to prepare a demo project the next week.

**Comment by avarabyeu** [comment]
@cheryomushkin 
could you please replace 
'com.epam.reportportal:agent-java-testng:3.0.0-BETA-6' with RC1

**Comment by cheryomushkin** [comment]
I created a test project. Please, find it attached. I couldn't reproduce this exact problem, but anyway it also reveals a problem with several test sections, which could be related somehow to the ticket issue.
So, after all tests are passed, I could see the only section in Report Portal which corresponds to the first `<test> ` section of the suite, the other twos are ignored.
[report portal test project.zip](https://github.com/reportportal/agent-java-testNG/files/926047/report.portal.test.project.zip)
Report portal installation:
```
Current version: Gateway Service: 3.0.0-BETA-3;
UI Service: 3.0.0-BETA-4;
Authorization Service: 3.0.0-BETA-6;
API Service: 3.0.0-BETA-6;
Registry Service: 3.0.0-BETA-2;

```

**Comment by avarabyeu** [comment]
Had a quick look at the project. Main problem here is that only TestOne extends TestBase which specifies ReportPortal's listener. This is why you see only first test at ReportPortal. The more interesting case is how to fix it. At the first look, you can extends other two classes from TestBase, but in this case TestNG will create three(!) instances of listener which leads to incorrect reporting (you should have the only one). The best option in your case is to specify listener on testng.xml level:
```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Report Portal Tests" verbose="2" configfailurepolicy="continue" parallel="classes" thread-count="2">

    <listeners>
        <listener class-name="com.epam.reportportal.testng.ReportPortalTestNGListener"/>
    </listeners>
    <test name="First">
        <packages>
            <package name="com.epum.one"/>
        </packages>
    </test>

    <test name="second">
        <packages>
            <package name="com.epum.two"/>
        </packages>
    </test>

    <test name="third">
        <packages>
            <package name="com.epum.three"/>
        </packages>
    </test>
</suite>
```
In this case, magic TestNG creates only one listener instance for the suite and reporting works correctly.

**Comment by avarabyeu** [comment]
@cheryomushkin could you please confirm that global listener fixes an issue?

**Comment by cheryomushkin** [comment]
@avarabyeu, yes global listener fixes the issue.

**Comment by avarabyeu** [comment]
cool. thanks a lot for raising it up!
