### ISSUE TITLE
"ItemID cannot be null" exception is thrown when test failed. 

### ISSUE THREAD

**Issue by OstapJ** [reportportal/agent-java-testNG#89]
*Prerequisites*
client agent-java-testng - 4.0.2 (https)
server 4.1.0

*Steps to reproduce*
1. Assert.fail in BeforeClass section
2. Run the test

*Expected Result*: Test is skipped
*Actual Result*: test throws exception listed below:
`java.lang.IllegalArgumentException: ItemID should not be null
        at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:230)
        at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
        at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
        at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1042)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)`

[AdditionalStackTrace.txt](https://github.com/reportportal/reportportal/files/2068287/AdditionalStackTrace.txt)

*Note* We tested on different testng adapter versions:
client agent-java-testng - 3.0.6 (http) - issue isn't reproducible
client agent-java-testng - 3.0.6 (https) - issue is reproducible
client agent-java-testng - 4.0.2 (https) - issue is reproducible

Report Portal is on http 8080. ELB redirects traffic from http to https.
Hence the issue is on client side.

The issue is critical because launches don't finish.

**Comment by HardNorth** [comment]
@OstapJ please try using the latest TestNG agent with TestNG 7.1.1: https://bintray.com/epam/reportportal/agent-java-testng/4.2.3

**Comment by ERankur91** [comment]
@HardNorth 
Is there any work around to resolve this issue in testng v:7.0.0. ?

**Comment by HardNorth** [comment]
@ERankur91 No, just use the newer version of TestNG agent. TestNG v6 and v7 are binary incompatible. And there will be no support for v6 in further versions of RP.
