### ISSUE TITLE
Nested Steps. NPE on handling null-vallued method arguments by StepAspect

### ISSUE THREAD

**Issue by alex-i-rybkin** [reportportal/agent-java-testNG#98]
Suggestion:
Handle nulls as "null" strings in such a case, not to fail the whole execution.

Example below:

>     @Test()
>     public void test() {
>         step(null);
>     }
> 
>     @Step("Simple step")
>     public void step(Object o) {
>         System.out.println(o);
>     }
> 

> java.lang.NullPointerException: null value in entry: ...
> 	at rp.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
> 	at rp.com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:176)
> 	at rp.com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:285)
> 	at com.epam.reportportal.aspect.StepNameUtils.createParamsMapping(StepNameUtils.java:70)
> 	at com.epam.reportportal.aspect.StepNameUtils.getStepName(StepNameUtils.java:52)
> 	at com.epam.reportportal.aspect.StepRequestUtils.buildStartStepRequest(StepRequestUtils.java:45)
> 	at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:83)

**Comment by alex-i-rybkin** [comment]
same as https://github.com/reportportal/client-java/issues/73
